apiVersion: apps/v1
kind: StatefulSet                               
metadata:
  name: rabbitmq
spec:
  replicas: 1                                               
  selector:
    matchLabels:                                         
      app: rabbitmq 
  serviceName: rabbitmq-headless     
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      nodeName: k8s.node1  
      containers:                                          
      - name: rabbitmq                                    
        image: rabbitmq:3.8.3-management                               
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - name: manager 
          containerPort: 15672
        - name: mq
          containerPort: 5672                    
        env:                                                   
        - name: RABBITMQ_DEFAULT_USER
          value: "root"        
        - name: RABBITMQ_DEFAULT_PASS
          value: "root"
        livenessProbe:
          tcpSocket:
            port: mq
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2
        readinessProbe:
          tcpSocket:
            port: mq
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        volumeMounts:                                
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq                           
      volumes:                                            
      - name: rabbitmq-data
        hostPath:
          path: /root/k8s-yml/rabbitmq/single/data                   
          type: DirectoryOrCreate
---
apiVersion: "v1"
kind: Service
metadata: 
  name: rabbitmq-headless
  namespace: default
spec: 
  selector: 
    app: rabbitmq
  type: ClusterIP  
  clusterIP: None
  ports: 
  - name: mq
    port: 5672 
    targetPort: 5672  
    protocol: "TCP" 
  - name: manager
    port: 15672 
    targetPort: 15672  
    protocol: "TCP" 
---
apiVersion: "v1"
kind: Service
metadata: 
  name: rabbitmq
  namespace: default
spec: 
  type: NodePort  
  selector: 
    app: rabbitmq
  ports: 
  - name: mq
    port: 5672 
    nodePort: 30006  
    protocol: "TCP" 
---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: rabbitmqmanager.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rabbitmq-headless
            port:
              number: 15672