---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-nodeport
  labels:
    app: gitlab
spec:
  ports:
    - name: gitlab-ui
      nodePort: 30020
      protocol: TCP
      targetPort: 30020
      port: 30020
    - name: gitlab-ssh
      port: 30022
      protocol: TCP
      targetPort: 30022
      nodePort: 30022
  selector:
    app: gitlab
  type: NodePort
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  # strategy:
  #   type: Recreate
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      # serviceAccountName: gitlab
      nodeName: k8s.node1
      containers:
        - image: gitlab/gitlab-ce:14.8.5-ce.0
          name: gitlab
          resources:
            requests:
              cpu: "2000m"
              memory: 4Gi
            limits:
              cpu: "2000m"
              memory: 8Gi
          securityContext:
            privileged: true
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_OMNIBUS_CONFIG
              value: |
                # postgresql['enable'] = false
                # gitlab_rails['db_username'] = "gitlab"
                # gitlab_rails['db_password'] = "bogeusepg"
                # gitlab_rails['db_host'] = "postgresql-headless"
                # gitlab_rails['db_port'] = "5432"
                # gitlab_rails['db_database'] = "gitlabhq_production"
                # gitlab_rails['db_adapter'] = 'postgresql'
                # gitlab_rails['db_encoding'] = 'utf8'
                # redis['enable'] = false
                # gitlab_rails['redis_host'] = 'redis-headless'
                # gitlab_rails['redis_port'] = '6379'
                # gitlab_rails['redis_password'] = 'it9s2cu'
                gitlab_rails['gitlab_shell_ssh_port'] = 30022
                external_url 'http://gitlab.example.com:30020/'
                gitlab_rails['initial_root_password'] = '12345678'
                nginx['listen_port'] = 30020
                nginx['listen_https'] = false
                # nginx['redirect_http_to_https'] = false
                # nginx['redirect_http_to_https_port'] = 30080
                #-------------------------------------------
                # gitlab_rails['gitlab_email_enabled'] = true
                # gitlab_rails['gitlab_email_from'] = 'admin@boge.com'
                # gitlab_rails['gitlab_email_display_name'] = 'boge'
                # gitlab_rails['gitlab_email_reply_to'] = 'gitlab@boge.com'
                # gitlab_rails['gitlab_default_can_create_group'] = true
                # gitlab_rails['gitlab_username_changing_enabled'] = true
                # gitlab_rails['smtp_enable'] = true
                # gitlab_rails['smtp_address'] = "smtp.exmail.qq.com"
                # gitlab_rails['smtp_port'] = 465
                # gitlab_rails['smtp_user_name'] = "gitlab@boge.com"
                # gitlab_rails['smtp_password'] = "bogesendmail"
                # gitlab_rails['smtp_domain'] = "exmail.qq.com"
                # gitlab_rails['smtp_authentication'] = "login"
                # gitlab_rails['smtp_enable_starttls_auto'] = true
                # gitlab_rails['smtp_tls'] = true
                #-------------------------------------------
                # 关闭 promethues
                prometheus['enable'] = false
                # 关闭 grafana
                grafana['enable'] = false
                # # 减少内存占用
                # unicorn['worker_memory_limit_min'] = "200 * 1 << 20"
                # unicorn['worker_memory_limit_max'] = "300 * 1 << 20"
                # # 减少 sidekiq 的并发数
                # sidekiq['concurrency'] = 16
                # # 减少 postgresql 数据库缓存
                # postgresql['shared_buffers'] = "256MB"
                # # 减少 postgresql 数据库并发数量
                # postgresql['max_connections'] = 8
                # # 减少进程数   worker=CPU核数+1
                # unicorn['worker_processes'] = 2
                # nginx['worker_processes'] = 2
                # puma['worker_processes'] = 2
                # # puma['per_worker_max_memory_mb'] = 850
                # # 保留3天备份的数据文件
                # gitlab_rails['backup_keep_time'] = 259200
                #-------------------------------------------
          ports:
            - containerPort: 30020
              name: gitlab-ui
            - containerPort: 30022
              name: gitlab-ssh
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - "curl -s https://127.0.0.1:30020/-/health|grep -w 'GitLab OK'"
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - "curl -s https://127.0.0.1:30020/-/health|grep -w 'GitLab OK'"
          #   initialDelaySeconds: 120
          #   periodSeconds: 10
          #   timeoutSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 3
          volumeMounts:
            - mountPath: /etc/gitlab
              name: gitlab1
            - mountPath: /var/log/gitlab
              name: gitlab2
            - mountPath: /var/opt/gitlab
              name: gitlab3
            # - mountPath: /etc/localtime
            #   name: tz-config

      volumes:
        - name: gitlab1
          hostPath:
            path: /root/k8s-yml/gitlab/single/data 
            type: DirectoryOrCreate
          # persistentVolumeClaim:
          #   claimName: gitlab-etc-ver130806-pvc
        - name: gitlab2
          hostPath:
            path: /root/k8s-yml/gitlab/single/log 
            type: DirectoryOrCreate
          # persistentVolumeClaim:
          #   claimName: gitlab-log-ver130806-pvc
        - name: gitlab3
          hostPath:
            path: /root/k8s-yml/gitlab/single/opt
            type: DirectoryOrCreate 
          # persistentVolumeClaim:
          #   claimName: gitlab-opt-ver130806-pvc
        # - name: tz-config
        #   hostPath:
        #     path: /root/k8s-yml/gitlab/single/localtime
        #     type: FileOrCreate
      securityContext:
        runAsUser: 0
        fsGroup: 0
---