apiVersion: "apps/v1"
kind: Deployment
metadata: 
  name: nginx-deployment
  namespace: default
spec: 
  replicas: 3
  selector: 
    matchLabels:  #标签选择器指定
      app: nginx
      release: canary
    matchExpressions: #{key:"key",operator:"OPERATOR",values:[VAL1,VAL2]} operator:In,NotIn,Exists存在，NotExists不存在，前两个values必须为非空列表，后两个values必须为空列表
  strategy: 
    type: "RollingUpdate"  #更新类型：滚动更新
    rollingUpdate:
      maxSurge: 2 #和期望ready的副本数比，超过期望副本数最大比例（或最大值），这个值调的越大，副本更新速度越快。
      maxUnavailable: 0 #和期望ready的副本数比，不可用副本数最大比例（或最大值），这个值越小，越能保证服务稳定，更新越平滑；
  revisionHistoryLimit: 10 #最多保存历史版本数，用于回滚
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: nginx
        release: canary
        environment: qa
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - name: http
          containerPort: 80