---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1    
  template:
    metadata:
      labels:
        app: minio
    spec:
      nodeName: k8s.node1  
      containers:
      - name: minio
        image: harbor.templete.com/library/minio:latest
        imagePullPolicy: IfNotPresent
        args: ["server", "/data","--console-address",":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          value: it9s2cu!
        ports:
        - containerPort: 9000
          name: minio
          protocol: TCP
        - containerPort: 9001
          name: minio-console
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        hostPath:
          path: /root/k8s-yml/minio/single/data 
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: minio-np
spec:
  selector:
    app: minio
  type: NodePort
  ports:
  - port: 9001
    targetPort: 9001
    nodePort: 30026
    name: minio-console
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 9000
    name: minio
    ports:
  - port: 9001
    targetPort: 9001
    name: minio-console



