apiVersion: v1
kind: Namespace
metadata:
  name: spinnaker 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: minio
  name: minio
  namespace: spinnaker
spec:
  selector:
    matchLabels:
      app: minio
  replicas: 1    
  template:
    metadata:
      labels:
        app: minio
      namespace: spinnaker
    spec:
      nodeName: k8sn2 
      containers:
      - name: minio
        image: harbor.templete.com/library/minio:latest
        imagePullPolicy: IfNotPresent
        args: ["server", "/data","--console-address",":9001"]
        env:
        - name: MINIO_ROOT_USER
          value: admin
        - name: MINIO_ROOT_PASSWORD
          value: it9s2cu!
        ports:
        - containerPort: 9000
          name: minio
          protocol: TCP
        - containerPort: 9001
          name: minio-console
          protocol: TCP
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 1000m
            memory: 2048Mi
        volumeMounts:
        - name: minio-data
          mountPath: /data
      volumes:
      - name: minio-data
        hostPath:
          path: /root/k8s-yml/minio/single/data 
          type: DirectoryOrCreate
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: minio-np
#   namespace: spinnaker
# spec:
#   selector:
#     app: minio
#   type: NodePort
#   ports:
#   - port: 9001
#     targetPort: 9001
#     nodePort: 30026
#     name: minio-console
---
apiVersion: v1
kind: Service
metadata:
  name: minio-headless
  namespace: spinnaker
spec:
  selector:
    app: minio
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9000
    targetPort: 9000
    name: minio
  - port: 9001
    targetPort: 9001
    name: minio-console

---
apiVersion: "networking.k8s.io/v1"
kind: Ingress
metadata:
  name: minio-ingress
  namespace: spinnaker
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: minio.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio-headless
            port:
              number: 9001