apiVersion: apps/v1
kind: StatefulSet                               
metadata:
  name: mysql
spec:
  replicas: 1                                               
  selector:
    matchLabels:                                         
      app: mysql 
  serviceName: mysql      
  template:
    metadata:
      labels:
        app: mysql
    spec:
      nodeName: k8s.node1  
      containers:                                          #Pod里容器的定义部分
      - name: mysql                                     #容器的名称
        image: mysql:8.0.27                               #容器对应的docker镜像
        imagePullPolicy: IfNotPresent
        args: ["--default-authentication-plugin=mysql_native_password","--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
          requests:
            cpu: 1000m
            memory: 2048Mi
        ports:
        - containerPort: 3306                         #容器暴露的端口号
        env:                                                   #写入到容器内的环境容量
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        livenessProbe:
          exec:
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysqladmin", "ping"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        volumeMounts:                                #容器内挂载点的定义部分
        - name: mysql-data
          mountPath: /var/lib/mysql              #容器内mysql的数据目录
        - name: mysql-conf
          mountPath: /etc/mysql/conf.d             
        - name: mysql-logs
          mountPath: /var/log/mysql               
      volumes:                                             #本地需要挂载到容器里的数据卷定义部分
      - name: mysql-data
        hostPath:
          path: /root/k8s-yml/mysql/single/data                   #本地存放mysql数据的目录=
          type: DirectoryOrCreate
      - name: mysql-conf
        hostPath:
          path: /root/k8s-yml/mysql/single/conf                   
          type: DirectoryOrCreate
      - name: mysql-logs
        hostPath:
          path: /root/k8s-yml/mysql/single/logs                   
          type: DirectoryOrCreate
---
apiVersion: "v1"
kind: Service
metadata: 
  name: mysql-service
  namespace: default
spec: 
  type: NodePort  #ExternalName外部服务引入集群, ClusterIP仅用于集群内部通讯, NodePort接入集群外部流量, LoadBalancer接入云负载均衡器
  selector: 
    app: mysql
  # sessionAffinity: "ClientIP" #ClientIP客户端每次访问固定pod ,默认为None
  ports: 
  - name: http
    port: 3306 #集群内访问端口
    nodePort: 30001  #集群外访问地址
    protocol: "TCP" #协议 TCP,UDP