apiVersion: "apps/v1"
kind: ReplicaSet
metadata: 
  name: nginx-deployment
  namespace: default
spec: 
  replicas: 2
  selector: 
    matchLabels:  #标签选择器指定
      app: nginx
      release: canary
  template:
    metadata:
      name: nginx-pod
      labels: 
        app: nginx
        release: canary
        environment: qa
    spec:
      containers:
      - name: nginx-container
        image: nginx:latest
        ports:
        - name: http
          containerPort: 8080